imports:
    - { resource: database.yml }
services:
    florinp.messenger.controller:
        class: florinp\messenger\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @florinp.messenger.model
    
    florinp.messenger.listener:
        class: florinp\messenger\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @florinp.messenger.model
            - @user
        tags:
            - { name: event.listener }
            
    florinp.messenger.model:
        class: florinp\messenger\models\main_model
        arguments:
            - @config
            - @controller.helper
            - @dbal.conn
            - @user
            - @florinp.messenger.libs.database 

    florinp.messenger.libs.database:
        class: florinp\messenger\libs\database
        arguments:
            - @ext.manager
            - %florinp.messenger.database.messages%
